const directionsCollection = [
    {id:1973,libelle:"Logistique Informatique",value:"LOGIST",path:"CD13,DGS,DGA AG,DSISN,SASU,LOGIST",id_pere:152},
    {id:1972,libelle:"Gestion des Achats",value:"ACHATS", path:"CD13,DGS,DGA AG,DSISN,SGFA,ACHATS", id_pere:1970},
    {id:1971,libelle:"Contrôle de Gestion",value:"CTLGEST",path:"CD13,DGS,DGA AG,DSISN,SGFA,CTLGEST",	id_pere:1970},
    {id:1970,libelle:"Service de Gestion Financière et Achats",value:"SGFA"	,path:"CD13,DGS,DGA AG,DSISN,SGFA",id_pere:	128},
    {id:1969,libelle:"Pôle Gestion Technique Infrastructures",value:"PGTI",path:"CD13,DGS,DGA AG,DSISN,SESN,PGTI",id_pere:137},
    {id:1968,libelle:"Pôle Gestion Technique Applications",value:"PGTA"	,path:"CD13,DGS,DGA AG,DSISN,SESN,PGTA",id_pere:	137},
    {id:1967,libelle:"Pôle Datacenters",value:"PDC"	,path:"CD13,DGS,DGA AG,DSISN,SESN,PDC",id_pere:137},
    {id:1966,libelle:"Gestion des Sites Rue Saint-Sébastien",value:"STSEB",path:"CD13,DGS,DGA AG,DSISN,SAJ,STSEB",id_pere:129},
    {id:1784,libelle:"Pôle Opérations Réseaux et Télécommunication",value:"PORT",path:"CD13,DGS,DGA AG,DSISN,SESN,PORT",id_pere:137},
    {id:1783,libelle:"Gestion Administrative",value:"ADMINIST",path:"CD13,DGS,DGA AG,DSISN,SGFA,ADMINIST",id_pere:1970},
    {id:1477,libelle:"Pole Projets",value:"PPROJ",path:"CD13,DGS,DGA AG,DSISN,SCSN,PPROJ",id_pere:133},
    {id:1476,libelle:"Pole RSI",value:"PRSI",path:"CD13,DGS,DGA AG,DSISN,SCSN,PRSI",id_pere:133},
    {id:1283,libelle:"Direction générale adjointe administration générale",value:"DGA AG",path:"CD13,DGS,DGA AG",id_pere:14},
    {id:154,libelle:"Assistance aux Utilisateurs",value:"ASSIST",path:"CD13,DGS,DGA AG,DSISN,SASU,ASSIST",id_pere:152},
    {id:152,libelle:"Service Assistance et Services aux Utilisateurs",value:"SASU",path:"CD13,DGS,DGA AG,DSISN,SASU",id_pere:	128},
    {id:147,libelle:"Documentation Technique",value:"DOC",path:"CD13,DGS,DGA AG,DSISN,SQSCI,DOC",id_pere:	142},
    {id:146,libelle:"Sécurite des Systèmes d'Information",value:"SSI",path:"CD13,DGS,DGA AG,DSISN,SQSCI,SSI",id_pere:142},
    {id:144,libelle:"Pôle Urbanisation, Innovation et Intégration du SI",value:"PU2I",path:"CD13,DGS,DGA AG,DSISN,SCSN,PU2I",id_pere:	133},
    {id:143,libelle:"Qualite et Contrôle Interne",value:"QCI",path:"CD13,DGS,DGA AG,DSISN,SQSCI,QCI",id_pere:	142},
    {id:142,libelle:"Service Qualité Sécurité et Contrôle Interne",value:"SQSCI",path:"CD13,DGS,DGA AG,DSISN,SQSCI",id_pere:128},
    {id:138,libelle:"Pôle Opérations Serveurs et Applications",value:"POSA"	,path:"CD13,DGS,DGA AG,DSISN,SESN,POSA",id_pere:137},
    {id:137,libelle:"Service Exploitation des Services Numériques",value:"SESN",path:"CD13,DGS,DGA AG,DSISN,SESN",id_pere:128},
    {id:133,libelle:"Service Construction des Services Numériques",value:"SCSN",path:"CD13,DGS,DGA AG,DSISN,SCSN",id_pere:128},
    {id:132,libelle:"Gestion Des Marches",value:"MARCHES",path:"CD13,DGS,DGA AG,DSISN,SAJ,MARCHES",id_pere:129},
    {id:130,libelle:"Comptabilite",value:"COMPTA",path:"CD13,DGS,DGA AG,DSISN,SAJ,COMPTA",id_pere:129},
    {id:129,libelle:"Service Administratif et Juridique",value:"SAJ",path:"CD13,DGS,DGA AG,DSISN,SAJ",id_pere:128},
    {id:128,libelle:"Direction des Systèmes d'Information et des Services Numériques",value:"DSISN"	,path:"CD13,DGS,DGA AG,DSISN",id_pere:1283},
    {id:14,libelle:	"Direction générale des services",value:"DGS",path:"CD13,DGS",id_pere:1},
    {id:1,libelle:"Conseil Départemental des Bouches du Rhône",value:"CD13"	,path:"CD13",id_pere:null},
]

const dataInJson = JSON.stringify(directionsCollection)